/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: Cinnamine (https://sketchfab.com/n0thaikal)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/game-ready-scifi-helmet-ff4c8308932447ac9ac831155fb63992
title: GAME READY SCIFI HELMET
*/

import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(
    GLTFLoader,
    '/models/helmet/scene.gltf',
    draco('/draco-gltf/')
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[10, 10, 10]}>
            <mesh
              material={materials.rubber}
              geometry={nodes.Plane008_rubber_0.geometry}
            />
            <mesh
              material={materials.metal}
              geometry={nodes.Plane008_metal_0.geometry}
            />
            <mesh
              material={materials.main}
              geometry={nodes.Plane008_main_0.geometry}
            />
            <mesh
              material={materials.maskfront}
              geometry={nodes.Plane008_maskfront_0.geometry}
            />
            <mesh
              material={materials.secondmain}
              geometry={nodes.Plane008_secondmain_0.geometry}
            />
            <mesh
              material={materials.visor}
              geometry={nodes.Plane008_visor_0.geometry}
            />
            <mesh
              material={materials.metal2}
              geometry={nodes.Plane008_metal2_0.geometry}
            />
            <mesh
              material={materials.emit}
              geometry={nodes.Plane008_emit_0.geometry}
            />
          </group>
        </group>
      </group>
    </group>
  )
}
